// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgUanGyPqIDrEbUgkbmKKREqaSXVnuZjA',
    appId: '1:453459214094:web:8f418b31698536a3fce15f',
    messagingSenderId: '453459214094',
    projectId: 'chatty-d292f',
    authDomain: 'chatty-d292f.firebaseapp.com',
    storageBucket: 'chatty-d292f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALAqKkknyrLm-Rnkez3jCCEDxU_E3cwDA',
    appId: '1:453459214094:android:dbc1b8e89680af3ffce15f',
    messagingSenderId: '453459214094',
    projectId: 'chatty-d292f',
    storageBucket: 'chatty-d292f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXVDmsd2iED45vFXg-WOgyaSIkkxm08zw',
    appId: '1:453459214094:ios:fa27ec72dce07e2cfce15f',
    messagingSenderId: '453459214094',
    projectId: 'chatty-d292f',
    storageBucket: 'chatty-d292f.appspot.com',
    androidClientId: '453459214094-4c329pfivdni02oe82ej1a82hdug6mj2.apps.googleusercontent.com',
    iosClientId: '453459214094-t8l05km0sef60e26fjr3tngnjlhbrek5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatty',
  );
}
